name: PHP Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: app
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pdo, pdo_pgsql
        coverage: xdebug
        tools: composer:v2, phpunit

    - name: Create .env file
      run: |
        cat > .env << EOF
        APP_ENV=${{ secrets.APP_ENV || 'testing' }}
        DB_HOST=${{ secrets.DB_HOST || 'localhost' }}
        DB_PORT=${{ secrets.DB_PORT || '5432' }}
        DB_NAME=${{ secrets.DB_NAME || 'app' }}
        DB_USER=${{ secrets.DB_USER || 'app' }}
        DB_PASSWORD=${{ secrets.DB_PASSWORD || 'app' }}
        PORT=${{ secrets.PORT || '8000' }}
        DB_READY_TIMEOUT=${{ secrets.DB_READY_TIMEOUT || '30' }}
        TEST_SERVER_PORT=${{ secrets.TEST_SERVER_PORT || '8001' }}
        EOF

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run database migrations
      run: php scripts/migrate.php

    - name: Run unit tests
      run: vendor/bin/phpunit --testsuite Unit --testdox

    - name: Run controller tests
      run: vendor/bin/phpunit --testsuite Controller --testdox

    - name: Start test server for integration tests
      run: php -S localhost:8001 public/index.php &
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: app
        DB_USER: app
        DB_PASSWORD: app

    - name: Wait for server to start
      run: sleep 5

    - name: Run integration tests
      run: vendor/bin/phpunit --testsuite Integration --testdox
      env:
        TEST_SERVER_URL: http://localhost:8001